### ISSUE TITLE
Invert SVC icon color

### ISSUE THREAD

**Issue by tskomudek** [nocode-js/sequential-workflow-designer#124]
Hi Bart,

i'm currently into styling and while i've found many things that can be customized,
i may have overlooked this one: Is there a way to set the stroke color for the svg-icons ?

![image](https://github.com/nocode-js/sequential-workflow-designer/assets/10913215/97753f61-e246-4e7c-a31e-64fc954b9f65)

Thank you

Tilo

**Comment by b4rtaz** [comment]
Hello @tskomudek!

The designer renders icons as `<image>` on the canvas and `<img>` in the HTML. Therefore, we cannot change colors as easily as we can for other elements. Especially since icons may be raster graphics. That what you can do is prepare your images adjusted to your theme. If you are using multiple themes, then you need to create the same icon in multiple variants.

```ts
function iconUrlProvider(step) {
  if (step.type === 'sendEmail') {
    if (theme === 'light') return './icon-send-email-light.svg';
    if (theme === 'dark') return './icon-send-email-dark.svg';
  }
  // ...
}
```

Another possibility is to use CSS to invert colors of image by using filters. But this feature works only in [modern browsers](https://developer.mozilla.org/en-US/docs/Web/CSS/filter-function/invert).

```css
.sqd-theme-dark .sqd-toolbox-item-icon-image,
.sqd-theme-dark .sqd-workspace-canvas image {-webkit-filter: invert(100%); filter: invert(100%);}
```
