### ISSUE TITLE
render Id as attribute in svg items

### ISSUE THREAD

**Issue by MrMoronIV** [nocode-js/sequential-workflow-designer#135]
Hi,

Could you add the id of the task, switch, any element in general to the group or rect of the svg items as an attribute? This way we can target it with CSS, thanks!

**Comment by b4rtaz** [comment]
Hello @MrMoronIV!

Currently, the designer is adding a type of a step to the class list (`sqd-type-{type}`). Do you need an id, or a task type?

**Comment by MrMoronIV** [comment]
I need the actual internal id of the task etc. on the svg element :)

**Comment by b4rtaz** [comment]
The 0.19.4 version now generates the `data-step-id` attribute for root `<g>` elements of step components. Example CSS selector:

```css
.sqd-workspace-canvas g[data-step-id="6cc1da8be15b9c3173a2effc09705c2e"] rect {fill: red !important;}
```
