### ISSUE TITLE
Is there any setting to set width of toolbar and steps?

### ISSUE THREAD

**Issue by johnmcclanes001** [nocode-js/sequential-workflow-designer#59]
![image](https://github.com/nocode-js/sequential-workflow-designer/assets/60515523/b6e626e0-665e-4ee1-88ae-08a58494d55c)

I want to increase the width of toolbar[ToolBox] and steps inside the toolbar.
can we have any configuration for this?

**Comment by b4rtaz** [comment]
Hi @johnmcclanes001! We need to add this feature. For now you may apply the workaround by CSS:

```css
.sqd-toolbox {width: 200px !important;}
.sqd-toolbox-filter, .sqd-toolbox-item {width: 180px !important;} /* 200px - 20px */
```
